### ISSUE TITLE
Clean out old data so backups do not lock tables required by logger-service for new data

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/logger-service#17]
Dave suggests:

> My first thought was just fix it all in MySQL
> 1) Archive the log_event and log_details tables
> 2) Generate the summaries one last time for these tables
> 3) Change the summary scripts to aggregate log_event and log_details, but then add in the results of the archived summaries
> 
> i think it'll just be a relatively easy change
> 
> just a "INSERT INTO event_summary_breakdown_email SELECT * from archived2018_event_summary_breakdown_email"
> at the end

**Comment by djtfmartin** [comment]
Done. 

I've done this is a rather manual manner but left some documentation here:

https://github.com/AtlasOfLivingAustralia/logger-service
