### ISSUE TITLE
Allow CSV downloads to optionally set an entityUid 

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/logger-service#23]
Required for metrics data studio reports.

If the `entityUid` param is omitted from the request, then the resulting CSV only contains the first (header) row - no data is provided.

Fix is to include data for all `entitityUid`s in the system, similar to how the JSON services work.

**Comment by Rita-C** [comment]
Hi @nickdos changes in #31 means `entityUid` is mandatory for source breakdown CSV download, so this ticket has been partially reverted back.

**Comment by Rita-C** [comment]
Ticket closed due to requirement change, see comment above.
