### ISSUE TITLE
Make entityUid an optional param on reasonBreakdownMonthly

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/logger-service#26]
https://logger.ala.org.au/service/reasonBreakdownMonthly?eventId=1002&entityUid=in4&sourceId=2001 

is an example request from logger home page. It would be useful to show this for all data resources (`entityUid` values). Currently it returns `400 - Request is missing eventId and/or entityUid` when not set.

**Comment by Rita-C** [comment]
comment made.

**Comment by nickdos** [comment]
Fixed missing error message change.

**Comment by nickdos** [comment]
Reverted due to issue identified in #31.
