### ISSUE TITLE
Scaffolding admin screen for `LogSourceType` throws an error on save

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/logger-service#33]
https://logger-test.ala.org.au/admin/logSourceType/create

- [x] Needs to have an input for `ID` so the user can specify the ID, so it is the same for prod and test
- [x] Hitting save results in an error and the entity is not saved to DB

**Comment by nickdos** [comment]
`ids for this class must be manually assigned before calling save(): au.org.ala.logger.LogSourceType`

**Comment by nickdos** [comment]
Works in test env. Needs code review and QA.

**Comment by Rita-C** [comment]
Code reviewed.

**Comment by Rita-C** [comment]
Tested create, edit and delete, all passed.
