### ISSUE TITLE
Reason breakdown link should work without entityUID

### ISSUE THREAD

**Issue by Rita-C** [AtlasOfLivingAustralia/logger-service#46]
link to https://github.com/AtlasOfLivingAustralia/logger-service/issues/31

ALA homepage calls dashboard for stats and dashboard is throwing an error for the call. Turns out it is calling https://logger.ala.org.au/service/reasonBreakdown?eventId=1002 which is requiring an entityUid.

**Comment by Rita-C** [comment]
@djtfmartin , could you please review this change? Thanks.

**Comment by Rita-C** [comment]
Change deployed to logger-test

**Comment by djtfmartin** [comment]
@Rita-C LGTM
