### ISSUE TITLE
OIDC 

### ISSUE THREAD

**Issue by yasima-csiro** [AtlasOfLivingAustralia/logger-service#48]
This task has following items:

- Grails 4 migration
- Dev CAS - ClientId and Client secret key for OpenConnect integration - https://auth-dev.ala.org.au/cas-management/management/registry/oauth
- Migration of current auth plugin version - 3.2.3 replace by ala-ws-security-plugin-5.0.0-SNAPSHOT
- Add OpenID connect authentication and JWT support
- Create OpenAPI definitions for the APIs
- Upload the API list to the test AWS API Gateway service.

**Comment by yasima-csiro** [comment]
https://github.com/AtlasOfLivingAustralia/logger-service/tree/feature/oidcIntegration

https://github.com/AtlasOfLivingAustralia/logger-service/commit/2db5bbdc8dc8009acb1d95261afa81a639069670

**Comment by yasima-csiro** [comment]
Ready to hand over to the team.

**Comment by sughics** [comment]
Release with 4.1.0
