### ISSUE TITLE
Adding new download reasons NOT trivial

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/logger-service#9]
[Download Reasons_Lee_Miles.xlsx](https://github.com/AtlasOfLivingAustralia/logger-service/files/179116/Download.Reasons_Lee_Miles.xlsx)

@M-Nicholls wants to add 2 new reasons and deprecate an existing reason and we've determined this is "too hard" due to it requiring code changes. Thus this issue.

We want to deprecate `scientific research` (too vague and covers most of the other reasons) and want to add `citizen science` and `restoration/remediation`.

The problem is:
- we can't deprecate an existing reason - so this needs an extra domain property (boolean)
- if we add a new reason, its `id` will be greater than testing (10) and thus it will appear after testing in the list. There are a few ways to get around this - add an `order` fields or sort reasons alphabetically and hope testing is last, etc.

**Comment by ansell** [comment]
Could you add another column for ordering purposes and use it instead of the id?

**Comment by ansell** [comment]
Just occurred to me that there were two options at the end there, and "add an order field" was a suggestion on its own :+1:

**Comment by nickdos** [comment]
This has been at some point, as domain class shows both `isDeprecated` and `defaultOrder` properties now.

Was done in commit 0d45632 .
